### ISSUE TITLE
NameError: name 'StockMarketBaiDu' is not defined

### ISSUE THREAD

**Issue by bigbigbigfish** [1nchaos/adata#11]
获取日K报错：

Traceback (most recent call last):
  File "main.py", line 2, in <module>
    res_df = adata.stock.market.get_market(stock_code='000100', k_type=1, start_date='2021-01-01')
  File "/home/bigfish/.local/lib/python3.8/site-packages/adata/stock/market/stock_market/stock_market.py", line 32, in get_market
    return StockMarketBaiDu().get_market(stock_code=stock_code, start_date=start_date, k_type=k_type)
NameError: name 'StockMarketBaiDu' is not defined

**Comment by 1nchaos** [comment]
fixed
1. 更新版本到0.0.25b0
pip install -U adata -i https://pypi.org/simple
2. 拉取最新的代码
3. 已加入到感谢列表

最后，感谢您的反馈
