### ISSUE TITLE
get_capital_flow接口是不是已经改了？

### ISSUE THREAD

**Issue by tttsss-01** [1nchaos/adata#113]
```
(.venv) stone@MAIN:~/trade$ /home/stone/trade/.venv/bin/python /home/stone/trade/.venv/lib/python3.10/site-packages/adata/stock/market/capital_flow/stock_capital_flow_baidu.py
Traceback (most recent call last):
  File "/home/stone/trade/.venv/lib/python3.10/site-packages/requests/models.py", line 974, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/stone/trade/.venv/lib/python3.10/site-packages/simplejson/__init__.py", line 514, in loads
    return _default_decoder.decode(s)
  File "/home/stone/trade/.venv/lib/python3.10/site-packages/simplejson/decoder.py", line 386, in decode
    obj, end = self.raw_decode(s)
  File "/home/stone/trade/.venv/lib/python3.10/site-packages/simplejson/decoder.py", line 416, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stone/trade/.venv/lib/python3.10/site-packages/adata/stock/market/capital_flow/stock_capital_flow_baidu.py", line 104, in <module>
    print(StockCapitalFlowBaidu().get_capital_flow_min(stock_code='300059'))
  File "/home/stone/trade/.venv/lib/python3.10/site-packages/adata/stock/market/capital_flow/stock_capital_flow_baidu.py", line 34, in get_capital_flow_min
    data_str = res.json()["Result"]["content"]["fundFlowMinute"]["data"]
  File "/home/stone/trade/.venv/lib/python3.10/site-packages/requests/models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)


```

**Comment by 1nchaos** [comment]
没有改，你在多看看呢
