### ISSUE TITLE
运行“获取A股所有股票代码信息列表”报错

### ISSUE THREAD

**Issue by Triones009** [1nchaos/adata#42]
运行以下代码：
import adata
df = adata.stock.info.all_code()
print(df)
报错：
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\pythonProject3\chap8\用AData获取所有的股票代码.py", line 3, in <module>
    df = adata.stock.info.all_code()
  File "C:\Users\Admin\anaconda3\lib\site-packages\adata\stock\info\stock_code.py", line 44, in all_code
    code = pd.read_csv(get_code_csv_path())[['stock_code', 'list_date2']]
  File "C:\Users\Admin\anaconda3\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Admin\anaconda3\lib\site-packages\pandas\io\parsers\readers.py", line 678, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\Admin\anaconda3\lib\site-packages\pandas\io\parsers\readers.py", line 575, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "C:\Users\Admin\anaconda3\lib\site-packages\pandas\io\parsers\readers.py", line 932, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "C:\Users\Admin\anaconda3\lib\site-packages\pandas\io\parsers\readers.py", line 1216, in _make_engine
    self.handles = get_handle(  # type: ignore[call-overload]
  File "C:\Users\Admin\anaconda3\lib\site-packages\pandas\io\common.py", line 786, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Admin\\anaconda3\\lib\\site-packages\\adata\\stock\\cache/code.csv'

进程已结束,退出代码1
我的运行环境 pycharm 2303.1.4   python解释器版本3.9。 pandas版本1.4.4  请问是否需要把pandas版本升级到目前最新的2.1.1

**Comment by 1nchaos** [comment]
pip install -U adata -i https://pypi.org/simple
升级一下版本：1.1.1，缓存文件缺失了

**Comment by Triones009** [comment]
非常感谢，按你的要求升级了版本，就正常了。之前我还打开了stock_code.py研究了一会，但看了一会就头疼了。
