### ISSUE TITLE
部分基金数据获取抛出异常

### ISSUE THREAD

**Issue by baei2048** [1nchaos/adata#81]
**Describe the bug**
调用如下接口，参数“515670”，报异常
adata.fund.market.get_market_etf("515670")

**To Reproduce**
1. pip install adata
2. open a new .py file and paste following
import adata
adata.fund.market.get_market_etf("515670")
3. 
Run

**Expected behavior**
Function crash

**Screenshots**
Crash Log:
Traceback (most recent call last):
  File "d:\projects\outsource_data\main.py", line 37, in <module>
    adata.fund.market.get_market_etf("515670")
  File "d:\InstalledApp\conda\envs\outsource_data\lib\site-packages\adata\fund\market\etf_market.py", line 30, in get_market_etf
    return self.ths.get_market_etf_ths(fund_code, k_type, start_date, end_date)
  File "d:\InstalledApp\conda\envs\outsource_data\lib\site-packages\adata\fund\market\etf_market_ths.py", line 50, in get_market_etf_ths
    result_df = pd.DataFrame(data=data, columns=['trade_date', 'open', 'high', 'low', 'close', 'volume', 'amount'])
  File "d:\InstalledApp\conda\envs\outsource_data\lib\site-packages\pandas\core\frame.py", line 851, in __init__
    arrays, columns, index = nested_data_to_arrays(
  File "d:\InstalledApp\conda\envs\outsource_data\lib\site-packages\pandas\core\internals\construction.py", line 520, in nested_data_to_arrays    arrays, columns, index = nested_data_to_arrays(
  File "d:\InstalledApp\conda\envs\outsource_data\lib\site-packages\pandas\core\internals\construction.py", line 845, in to_arraysuction.py", line 520, in nested_data_to_arrays
    arrays, columns = to_arrays(data, columns, dtype=dtype)                                     uction.py", line 942, in _finalize_columns_and_data
  File "d:\InstalledApp\conda\envs\outsource_data\lib\site-packages\pandas\core\internals\construction.py", line 845, in to_arrays
    content, columns = _finalize_columns_and_data(arr, columns, dtype)
  File "d:\InstalledApp\conda\envs\outsource_data\lib\site-packages\pandas\core\internals\construction.py", line 942, in _finalize_columns_and_data
    raise ValueError(err) from err
ValueError: 7 columns passed, passed data had 1 columns

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser Chrome
 - Python 3.10

**Additional context**
看上去是没有处理数据源返回的“空数据”。

**Comment by baei2048** [comment]
517270， 517760，159646，159693，159769，159971 这几个参数同样的问题。

**Comment by 1nchaos** [comment]
这个确实没有想过的数据了，后续增加了空数据判断

**Comment by 1nchaos** [comment]
更新到v2.4.0
