### ISSUE TITLE
adata.fund.market.get_market_etf 接口参数传“159971”报错

### ISSUE THREAD

**Issue by Yzx-1024** [1nchaos/adata#97]
**Describe the bug**
adata.fund.market.get_market_etf 接口参数传“159971”报错

**To Reproduce**
配置python环境
安装adata包
执行：adata.fund.market.get_market_etf("159971")

**Expected behavior**
获取行情数据

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome

**Additional context**
crash log
d:\InstalledApp\conda\envs\outsource_data\lib\site-packages\adata\fund\market\etf_market_ths.py:54: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  result_df['trade_time'] = pd.to_datetime(result_df['trade_date']).dt.strftime('%Y-%m-%d %H:%M:%S')
Traceback (most recent call last):
  File "parsing.pyx", line 684, in pandas._libs.tslibs.parsing.dateutil_parse
ValueError: day is out of range for month

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "d:\projects\outsource_data\main.py", line 45, in <module>
    r = adata.fund.market.get_market_etf("159971")
  File "d:\InstalledApp\conda\envs\outsource_data\lib\site-packages\adata\fund\market\etf_market.py", line 30, in get_market_etf
    return self.ths.get_market_etf_ths(fund_code, k_type, start_date, end_date)
  File "d:\InstalledApp\conda\envs\outsource_data\lib\site-packages\adata\fund\market\etf_market_ths.py", line 54, in get_market_etf_ths
    result_df['trade_time'] = pd.to_datetime(result_df['trade_date']).dt.strftime('%Y-%m-%d %H:%M:%S')
  File "d:\InstalledApp\conda\envs\outsource_data\lib\site-packages\pandas\core\tools\datetimes.py", line 1067, in to_datetime
    values = convert_listlike(arg._values, format)
  File "d:\InstalledApp\conda\envs\outsource_data\lib\site-packages\pandas\core\tools\datetimes.py", line 435, in _convert_listlike_datetimes
    result, tz_parsed = objects_to_datetime64(
  File "d:\InstalledApp\conda\envs\outsource_data\lib\site-packages\pandas\core\arrays\datetimes.py", line 2398, in objects_to_datetime64
    result, tz_parsed = tslib.array_to_datetime(
  File "tslib.pyx", line 414, in pandas._libs.tslib.array_to_datetime
  File "tslib.pyx", line 596, in pandas._libs.tslib.array_to_datetime
  File "tslib.pyx", line 553, in pandas._libs.tslib.array_to_datetime
  File "conversion.pyx", line 641, in pandas._libs.tslibs.conversion.convert_str_to_tsobject
  File "parsing.pyx", line 336, in pandas._libs.tslibs.parsing.parse_datetime_string
  File "parsing.pyx", line 688, in pandas._libs.tslibs.parsing.dateutil_parse
pandas._libs.tslibs.parsing.DateParseError: day is out of range for month: 0, at position 0

**Comment by 1nchaos** [comment]
update 2.5.7

**Comment by Yzx-1024** [comment]
已验证，bug close
